@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@gmail.com.br",
  "password": "12345"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "igorxuxicotrim@gmail.com",
  "password": "12345678"
}

###

# @name create_questions
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Qual a sua cor favorita?",
  "content": "Estou em dúvida entre azul e vermelho"
}
