@baseUrl = http://localhost:3333

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@gmail.com.br",
  "password": "12345"
}

###
# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "igorxuxicotrim@gmail.com",
  "password": "12345678"
}
