version: "3.8"

services:
  postgres:
    container_name: clean-forum-nest-pg
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: clean-forum-nest
    #   PGDATA: /data/postgres
    # volumes:
    #   - ./data/pg:/data/postgres
  cache:
    container_name: clean-forum-nest-cache
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data